import type { User, Swap, Feedback } from './types';

export const mockFeedback: Feedback[] = [
  { id: 'f1', swapId: 's1', reviewerId: 'u2', reviewedId: 'u1', rating: 5, comment: 'Amazing collaboration! Very knowledgeable.' },
  { id: 'f2', swapId: 's2', reviewerId: 'u3', reviewedId: 'u1', rating: 4, comment: 'Great to work with, very responsive.' },
  { id: 'f3', swapId: 's3', reviewerId: 'u1', reviewedId: 'u2', rating: 5, comment: 'Learned a lot about pottery. Highly recommend!' },
  { id: 'f4', swapId: 's4', reviewerId: 'u4', reviewedId: 'u3', rating: 5, comment: 'Fantastic baker and a great teacher.'},
  { id: 'f5', swapId: 's5', reviewerId: 'u5', reviewedId: 'u4', rating: 4, comment: 'Helpful with my marketing strategy.'},
  { id: 'f6', swapId: 's6', reviewerId: 'u1', reviewedId: 'u5', rating: 5, comment: 'Excellent guitar lessons.'},
  { id: 'f7', swapId: 's7', reviewerId: 'u6', reviewedId: 'u2', rating: 3, comment: 'Good, but scheduling was a bit difficult.'},
  { id: 'f8', swapId: 's8', reviewerId: 'u2', reviewedId: 'u6', rating: 5, comment: 'The best yoga instructor!'},
];

// We need to define users without feedback first, then assign feedback.
const usersBase: Omit<User, 'feedback'>[] = [
  {
    id: 'u1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/E91E63/FFFFFF.png',
    data_ai_hint: 'woman developer',
    location: 'San Francisco, CA',
    skillsOffered: ['Web Development', 'React', 'Node.js'],
    skillsWanted: ['Graphic Design', 'Pottery'],
    availability: 'evenings',
    profileStatus: 'public',
  },
  {
    id: 'u2',
    name: 'Bob Williams',
    email: 'bob@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/2196F3/FFFFFF.png',
    data_ai_hint: 'man designer',
    location: 'New York, NY',
    skillsOffered: ['Graphic Design', 'Illustration', 'Logo Design'],
    skillsWanted: ['Web Development', 'Yoga'],
    availability: 'weekends',
    profileStatus: 'public',
  },
  {
    id: 'u3',
    name: 'Charlie Brown',
    email: 'charlie@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/4CAF50/FFFFFF.png',
    data_ai_hint: 'man writer',
    location: 'Chicago, IL',
    skillsOffered: ['Creative Writing', 'Baking', 'Content Creation'],
    skillsWanted: ['Photography', 'Marketing'],
    availability: 'weekdays',
    profileStatus: 'public',
  },
  {
    id: 'u4',
    name: 'Diana Prince',
    email: 'diana@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/FFC107/FFFFFF.png',
    data_ai_hint: 'woman professional',
    location: 'Austin, TX',
    skillsOffered: ['Marketing Strategy', 'SEO', 'Social Media'],
    skillsWanted: ['Baking', 'Public Speaking'],
    availability: 'evenings',
    profileStatus: 'public',
  },
  {
    id: 'u5',
    name: 'Ethan Hunt',
    email: 'ethan@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/9C27B0/FFFFFF.png',
    data_ai_hint: 'man musician',
    location: 'Miami, FL',
    skillsOffered: ['Guitar Lessons', 'Music Production', 'Songwriting'],
    skillsWanted: ['Web Development', 'Cooking'],
    availability: 'weekends',
    profileStatus: 'public',
  },
  {
    id: 'u6',
    name: 'Fiona Glenanne',
    email: 'fiona@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/00BCD4/FFFFFF.png',
    data_ai_hint: 'woman instructor',
    location: 'Los Angeles, CA',
    skillsOffered: ['Yoga Instruction', 'Meditation', 'Fitness Coaching'],
    skillsWanted: ['Graphic Design', 'Gardening'],
    availability: 'weekdays',
    profileStatus: 'public',
  },
   {
    id: 'u7',
    name: 'George Costanza',
    email: 'george@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/795548/FFFFFF.png',
    data_ai_hint: 'man architect',
    location: 'New York, NY',
    skillsOffered: ['Architecture', 'Urban Planning'],
    skillsWanted: ['Latex Sales', 'Hand-modeling'],
    availability: 'private', // This user should not appear on the home page
  },
  {
    id: 'u8',
    name: 'Hannah Montana',
    email: 'hannah@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/F44336/FFFFFF.png',
    data_ai_hint: 'woman singer',
    location: 'Malibu, CA',
    skillsOffered: ['Singing', 'Stage Performance'],
    skillsWanted: ['Normal Life', 'Disguise'],
    availability: 'weekends',
    profileStatus: 'public',
  },
  {
    id: 'u9',
    name: 'Ian Malcolm',
    email: 'ian@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/3F51B5/FFFFFF.png',
    data_ai_hint: 'man scientist',
    location: 'Isla Nublar',
    skillsOffered: ['Chaos Theory', 'Witty Repartee'],
    skillsWanted: ['Dinosaur Taming', 'Helicopter Piloting'],
    availability: 'weekends',
    profileStatus: 'public',
  },
  {
    id: 'u10',
    name: 'Jane Smith',
    email: 'jane@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/673AB7/FFFFFF.png',
    data_ai_hint: 'woman analyst',
    location: 'Seattle, WA',
    skillsOffered: ['Data Analysis', 'Python', 'Machine Learning'],
    skillsWanted: ['Project Management', 'Public Speaking'],
    availability: 'weekdays',
    profileStatus: 'public',
  },
  {
    id: 'u11',
    name: 'Ken Adams',
    email: 'ken@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/8BC34A/FFFFFF.png',
    data_ai_hint: 'man photographer',
    location: 'Portland, OR',
    skillsOffered: ['Photography', 'Photo Editing', 'Videography'],
    skillsWanted: ['Creative Writing', 'SEO'],
    availability: 'weekends',
    profileStatus: 'public',
  },
  {
    id: 'u12',
    name: 'Laura Croft',
    email: 'laura@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/CDDC39/FFFFFF.png',
    data_ai_hint: 'woman adventurer',
    location: 'London, UK',
    skillsOffered: ['Archaeology', 'Rock Climbing', 'Ancient Languages'],
    skillsWanted: ['Web Development', 'Drone Piloting'],
    availability: 'evenings',
    profileStatus: 'public',
  },
  {
    id: 'u13',
    name: 'Michael Scott',
    email: 'michael@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/FF9800/FFFFFF.png',
    data_ai_hint: 'man manager',
    location: 'Scranton, PA',
    skillsOffered: ['Management', 'Sales', 'Improv Comedy'],
    skillsWanted: ['Graphic Design', 'Video Editing'],
    availability: 'weekdays',
    profileStatus: 'public',
  },
  {
    id: 'u14',
    name: 'Nancy Drew',
    email: 'nancy@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/FF5722/FFFFFF.png',
    data_ai_hint: 'woman detective',
    location: 'River Heights, IL',
    skillsOffered: ['Mystery Solving', 'Observation', 'Disguise'],
    skillsWanted: ['Data Analysis', 'Cybersecurity'],
    availability: 'weekends',
    profileStatus: 'public',
  },
  {
    id: 'u15',
    name: 'Oscar Martinez',
    email: 'oscar@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/607D8B/FFFFFF.png',
    data_ai_hint: 'man accountant',
    location: 'Scranton, PA',
    skillsOffered: ['Accounting', 'Financial Planning', 'Origami'],
    skillsWanted: ['Public Speaking', 'Marketing'],
    availability: 'evenings',
    profileStatus: 'public',
  },
  {
    id: 'u16',
    name: 'Pam Beesly',
    email: 'pam@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/009688/FFFFFF.png',
    data_ai_hint: 'woman artist',
    location: 'Scranton, PA',
    skillsOffered: ['Art', 'Illustration', 'Graphic Design'],
    skillsWanted: ['Web Development', 'Marketing Strategy'],
    availability: 'weekdays',
    profileStatus: 'public',
  },
  {
    id: 'u17',
    name: 'Quentin Tarantino',
    email: 'quentint@example.com',
    profilePhotoUrl: 'https://placehold.co/128x128/9E9E9E/FFFFFF.png',
    data_ai_hint: 'man director',
    location: 'Hollywood, CA',
    skillsOffered: ['Filmmaking', 'Screenwriting', 'Directing'],
    skillsWanted: ['Music Production', 'Animation'],
    availability: 'weekends',
    profileStatus: 'public',
  }
];

export const mockUsers: User[] = usersBase.map(user => ({
  ...user,
  feedback: mockFeedback.filter(f => f.reviewedId === user.id),
}));


export const mockSwaps: Swap[] = [
    { id: 's1', requesterId: 'u2', responderId: 'u1', offeredSkill: 'Graphic Design', wantedSkill: 'Web Development', message: 'Hey Alice, I can help with your branding if you can build a portfolio site for me.', status: 'completed', createdAt: new Date('2023-10-01') },
    { id: 's2', requesterId: 'u3', responderId: 'u1', offeredSkill: 'Baking', wantedSkill: 'Web Development', message: 'I can bake you the best cookies for a week for some help on my blog.', status: 'accepted', createdAt: new Date('2023-10-15') },
    { id: 's3', requesterId: 'u1', responderId: 'u2', offeredSkill: 'React', wantedSkill: 'Pottery', message: 'Looking to learn pottery, can teach you React in exchange!', status: 'pending', createdAt: new Date('2023-10-20') },
    { id: 's4', requesterId: 'u4', responderId: 'u3', offeredSkill: 'SEO', wantedSkill: 'Baking', message: 'I will get your food blog to the first page of Google for some sourdough lessons.', status: 'rejected', createdAt: new Date('2023-09-25') },
    { id: 's5', requesterId: 'u5', responderId: 'u4', offeredSkill: 'Guitar Lessons', wantedSkill: 'Marketing Strategy', message: 'Need help marketing my new album. Can teach you guitar.', status: 'pending', createdAt: new Date('2023-10-22') },
    { id: 's6', requesterId: 'u1', responderId: 'u5', offeredSkill: 'Node.js', wantedSkill: 'Guitar Lessons', message: 'Hi Ethan, I\'m a developer who would love to learn guitar. Can help with backend work.', status: 'accepted', createdAt: new Date('2023-10-18') },
    { id: 's7', requesterId: 'u6', responderId: 'u2', offeredSkill: 'Yoga Instruction', wantedSkill: 'Illustration', message: 'Can offer private yoga sessions for some custom illustrations for my studio.', status: 'completed', createdAt: new Date('2023-08-15') },
    { id: 's8', requesterId: 'u2', responderId: 'u6', offeredSkill: 'Logo Design', wantedSkill: 'Yoga Instruction', message: 'Hi Fiona, I can design a new logo for your yoga business in exchange for a few classes.', status: 'pending', createdAt: new Date('2023-10-21') },
];
